Update dojoProductType
sora-xor/Sora-iOS pull request #385
Opened 2024-01-18 15:58 UTC by marat-biriushev

Update dojoProductType

2024-01-19 10:41 UTC, C4tWithShell requested changes
It's not part of polkaswap. It's mobile app. We will separate it to the sora-mobile productType

2024-01-25 09:16 UTC, C4tWithShell approved these changes

2024-01-25 09:16 UTC, C4tWithShell commented on Jenkinsfile
> +@Library('jenkins-library@feature/DOPS-2956') _
Don't forget to remove it after you finish

2024-01-25 13:22 UTC, marat-biriushev commented on Jenkinsfile
> +@Library('jenkins-library@feature/DOPS-2956') _
Done

2024-01-25 13:44 UTC, merged